version: '2'
volumes:
  app-volume: 
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=default_user
      - MYSQL_ROOT_HOST=%
      - MYSQL_PASSWORD=default
      - MYSQL_DATABASE=i3database
    ports:
      - "3306:3306"
    volumes:
      - app-volume:/var/log/mosquitto
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
  django:
    build: 
      context: ./
      dockerfile: ./frontend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - app-volume:/var/log/mosquitto
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    links: 
      - mysql:mysql
    restart: on-failure
  mosquitto:
    build: ./backend/mqtt
    volumes:
      - app-volume:/var/log/mosquitto
    ports:
      - "9010:9010"
      - "1883:1883"
      - "9001:9001"
      - "8883:8883"
    links: 
      - mysql:mysql
    tty: true
    restart: on-failure
  parser_agent:
    build: 
      context: ./
      dockerfile: ./backend/parser_agent/Dockerfile
    links: 
      - mysql:mysql
    volumes:
      - app-volume:/var/log/mosquitto
