DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id INTEGER AUTO_INCREMENT,
	user_id INTEGER,
	username VARCHAR(100) NOT NULL,
	pw VARCHAR(1280) NOT NULL,
	super INT(1) NOT NULL DEFAULT 0,
	PRIMARY KEY (id),
	FOREIGN KEY (user_id) REFERENCES auth_user(id) ON DELETE CASCADE
  );

DROP TABLE IF EXISTS acls;

CREATE TABLE acls (
	id INTEGER AUTO_INCREMENT,
	user_id INTEGER,
	username VARCHAR(100) NOT NULL,
	topic VARCHAR(256) NOT NULL,
	topic_id INTEGER,
	rw INTEGER(1) NOT NULL DEFAULT 1,	-- 1: read-only, 2: read-write
	PRIMARY KEY (id),
	FOREIGN KEY (user_id) REFERENCES auth_user(id) ON DELETE CASCADE,
	FOREIGN KEY (topic_id) REFERENCES products_product(id) ON DELETE CASCADE
	);

